### ISSUE TITLE
Plugin does not work properly in FFXIV 4.2

### ISSUE THREAD

**Issue by TamanegiMage** [TamanegiMage/ACT_EnmityPlugin#1]

**Comment by Nan0bit** [comment]
Error: Enmity: Failed to signature scan (charmapAddress,targetAddress).
Error: Enmity List: Failed to signature scan (charmapAddress,targetAddress).

**Comment by quisquous** [comment]
private const string charmapSignature64 = "85AD????????8BD7488D0D";
private const int charmapOffset64 = 8;

That seems to work for me locally and I get my name in debug output.  Couldn't quite get the target offset to work yet.

**Comment by TamanegiMage** [comment]
Work in progress https://github.com/TamanegiMage/ACT_EnmityPlugin/commit/72b1d55c72eca842e35bc03c2524ab64c5fb4ee4 .  
I'm checking target structures.

I need enmitySignature64 value...

**Comment by Nemekh01** [comment]
Have been informed to consider this, hope it helps:
E8 ? ? ? ? 45 0F 2F C2 + B4h
emnitysignature64 + offset
